[package]
name = "todo"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "state of the art Check-list"


[dependencies]
itertools = "0.10.5"
thiserror = "2"
log = "0.4"
simple_logger = "5"
env_logger = "0.11"
chrono = "0.4"
colored = "2"